version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda

    working_directory: ~/superconv

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            conda env create -f cpu_environment.yml
            source activate cpu_superconv

      - run:
          name: run tests
          command: |
            source activate cpu_superconv
            python -m unittest discover -s tests

